# Generated by Django 2.1 on 2018-08-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('ancester', models.CharField(max_length=20, null=True)),
                ('content', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
